version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-task-database
    ports:
      - 5434:5432 # map port 5434 on host(pc) to 5432 in container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456@
      POSTGRES_DB: task-management-db
    networks:
      - nestjs-network
networks:
  nestjs-network:
